// src/screens/ProfileScreen.js
import React, { useEffect, useRef, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Platform,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  Pressable,
} from 'react-native';
import * as Linking from 'expo-linking';
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';
import { Ionicons } from '@expo/vector-icons';
import Screen from '../components/Screen';
import {
  isAdminCached,
  setAdminCached,
  subscribeAdmin,
} from '../utils/adminGate';
import { Colors } from '../constants/colors';
import { supabase } from '../supabase';
import FloatingLabelInput from '../components/FloatingLabelInput';
import { fetchESV } from '../utils/bible';

// Fallback: converts UUID → short, human-friendly base36 ID
function shortCodeFromUid(uid) {
  try {
    const hex = (uid || '').replace(/[^a-f0-9]/gi, '');
    const chunk = hex.slice(0, 10) || '0000000000';
    const num = parseInt(chunk, 16);
    return num.toString(36).toUpperCase().slice(0, 9);
  } catch {
    return (uid || '').slice(0, 9).toUpperCase();
  }
}

// Invisible hotspot: 5 taps within 2 seconds → Debug (admin/dev only)
function SecretTapHotspot({ onTrigger, enabled }) {
  const ref = useRef({ count: 0, timer: null });
  if (!enabled) return null;

  const onTap = () => {
    clearTimeout(ref.current.timer);
    ref.current.count += 1;
    ref.current.timer = setTimeout(() => {
      ref.current.count = 0;
    }, 2000);

    if (ref.current.count >= 5) {
      ref.current.count = 0;
      try {
        onTrigger?.();
      } catch {}
    }
  };

  return (
    <Pressable onPress={onTap} hitSlop={20} style={styles.secretHotspot}>
      <View />
    </Pressable>
  );
}

export default function ProfileScreen({ navigation }) {
  const [uid, setUid] = useState('');
  const [shortId, setShortId] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [verseRef, setVerseRef] = useState('');
  const [verseText, setVerseText] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const [finding, setFinding] = useState(false);
  const [findError, setFindError] = useState('');
  const [lastLookup, setLastLookup] = useState({ ref: '', text: '' });
  const [isAdminLocal, setIsAdminLocal] = useState(isAdminCached());

  // 🔐 Account / auth state
  const [isAnonymous, setIsAnonymous] = useState(false);
  const [authEmail, setAuthEmail] = useState('');
  const [accountEmailInput, setAccountEmailInput] = useState('');
  const [accountPasswordInput, setAccountPasswordInput] = useState('');
  const [accountLoading, setAccountLoading] = useState(false);
  const [showDebugButton, setShowDebugButton] = useState(false);

  // ---------- Load profile + auth ----------
  useEffect(() => {
    (async () => {
      try {
        const {
          data: { user },
          error: authError,
        } = await supabase.auth.getUser();

        if (authError || !user) {
          console.warn(
            'No active auth session. Ensure anonymous sign-in is running at app start.'
          );
          setLoading(false);
          return;
        }

        const myId = user.id;
        setUid(myId);

        // capture auth info
        setIsAnonymous(!!user.is_anonymous);
        setAuthEmail(user.email || '');
        if (user.email) setAccountEmailInput(user.email);

        // Try to fetch profile (including short_id)
        let { data, error } = await supabase
          .from('profiles')
          .select('display_name, verse_ref, verse_text, short_id')
          .eq('id', myId)
          .single();

        if (error && error.code === 'PGRST116') {
          // No row yet — create minimal row, then reselect to get short_id if generated by DB
          const { data: inserted, error: insErr } = await supabase
            .from('profiles')
            .insert({
              id: myId,
              display_name: '',
              verse_ref: '',
              verse_text: '',
            })
            .select('display_name, verse_ref, verse_text, short_id')
            .single();
          if (insErr) throw insErr;
          data = inserted;
        } else if (error) {
          throw error;
        }

        setDisplayName(data?.display_name || '');

        const initialRef = (data?.verse_ref || '').trim();
        const initialText = (data?.verse_text || '').trim();
        if (initialRef && initialText) {
          setLastLookup({ ref: initialRef, text: initialText });
        } else {
          setLastLookup({ ref: '', text: '' });
        }

        setVerseRef(data?.verse_ref || '');
        setVerseText(data?.verse_text || '');

        // Prefer DB short_id; otherwise derive one so user always sees something usable
        setShortId(data?.short_id || shortCodeFromUid(myId));
      } catch (e) {
        console.error('Profile load error:', e);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  useEffect(() => {
    const off = subscribeAdmin((flag) => {
      setIsAdminLocal(!!flag);
      setShowDebugButton(!!flag); // auto-hide if admin disabled elsewhere
    });
    return off;
  }, []);

  // ---------- Save profile ----------
  const onSave = async () => {
    const ref = (verseRef || '').trim();
    const fromLookup =
      !!ref &&
      !!verseText &&
      lastLookup.ref === ref &&
      lastLookup.text === verseText;

    if (ref && !fromLookup) {
      Alert.alert(
        'Find Verse Required',
        'Please use the “Find Verse” button to fetch the verse text for this reference before saving.'
      );
      return;
    }

    setSaving(true);
    try {
      const clean = (s) => (s && s.trim().length ? s.trim() : null);

      const { error } = await supabase
        .from('profiles')
        .upsert(
          {
            id: uid,
            display_name: clean(displayName),
            verse_ref: clean(verseRef),
            verse_text: clean(verseText),
          },
          { onConflict: 'id' }
        )
        .select();

      if (error) throw error;

      Alert.alert('Saved', 'Your profile has been updated.');

      // Navigate like before
      const toRoute = (s) => (s && s.trim().length ? s.trim() : '');
      navigation.navigate('MainTabs', {
        screen: 'Home',
        params: {
          verseRef: toRoute(verseRef),
          verseText: toRoute(verseText),
          refreshAt: Date.now(),
        },
      });
    } catch (e) {
      Alert.alert('Error', e.message || 'Failed to save.');
    } finally {
      setSaving(false);
    }
  };

  // ---------- Find verse from ESV ----------
  const onFindVerse = async () => {
    const ref = (verseRef || '').trim();
    if (!ref) {
      setFindError('Enter a verse reference (e.g., John 3:16)');
      return;
    }

    if (lastLookup.ref === ref && lastLookup.text) {
      setVerseText(lastLookup.text);
      setFindError('');
      return;
    }

    try {
      setFinding(true);
      setFindError('');
      const text = await fetchESV(ref);
      setVerseText(text);
      setLastLookup({ ref, text });
    } catch (e) {
      setFindError(e?.message || 'Lookup failed.');
    } finally {
      setFinding(false);
    }
  };

  // ---------- Upgrade anonymous → email/password ----------
  const onUpgradeAccount = async () => {
    const email = accountEmailInput.trim();
    const password = accountPasswordInput;

    if (!email || password.length < 6) {
      Alert.alert(
        'Email & password required',
        'Please enter a valid email and a password at least 6 characters long.'
      );
      return;
    }

    setAccountLoading(true);
    try {
      const redirectTo = Linking.createURL('auth');
      const { data, error } = await supabase.auth.signUp({
        email,
        password,
        options: { emailRedirectTo: redirectTo },
      });
      if (error) throw error;

      setAccountEmailInput('');
      setAccountPasswordInput('');

      Alert.alert(
        'Check your email',
        'We’ve sent you a confirmation link. After you confirm, come back to the app — your account will be linked to this email.'
      );

      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (user) {
        setIsAnonymous(!!user.is_anonymous);
        setAuthEmail(user.email || email);
      }
    } catch (e) {
      Alert.alert(
        'Account error',
        e?.message || 'Failed to create / upgrade your account.'
      );
    } finally {
      setAccountLoading(false);
    }
  };

  // ---------- Sign out ----------
  const onSignOut = () => {
    Alert.alert(
      'Sign out?',
      'You’ll be signed out. You can continue as a guest or sign back in.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Sign out',
          style: 'destructive',
          onPress: async () => {
            try {
              await supabase.auth.signOut();
              navigation.reset({ index: 0, routes: [{ name: 'Auth' }] });
            } catch (e) {
              Alert.alert(
                'Sign out error',
                e?.message || 'Failed to sign out. Please try again.'
              );
            }
          },
        },
      ]
    );
  };

  // ---------- Delete account + data ----------
  const onDeleteAccount = () => {
    Alert.alert(
      'Delete account?',
      'This will permanently delete your account, profile, journal entries, friendships, and encouragements.\n\nThis cannot be undone.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              setAccountLoading(true);
              const { error } = await supabase.rpc('delete_current_user');
              if (error) throw error;

              await supabase.auth.signOut();

              Alert.alert(
                'Account deleted',
                'Your account and data have been deleted.'
              );
              navigation.navigate('MainTabs', { screen: 'Home' });
            } catch (e) {
              Alert.alert(
                'Delete error',
                e?.message ||
                  'Failed to delete account. Please check your connection and try again.'
              );
            } finally {
              setAccountLoading(false);
            }
          },
        },
      ]
    );
  };

  // ---------- Save button enable logic ----------
  const canSave =
    !saving &&
    (!!displayName.trim() || !!verseRef.trim() || !!verseText.trim()) &&
    ((!verseRef.trim() && !verseText.trim()) ||
      (lastLookup.ref === (verseRef || '').trim() &&
        lastLookup.text === verseText));

  if (loading) {
    return (
      <Screen showBack onBack={() => navigation.goBack()}>
        <View style={styles.loadingWrap}>
          <ActivityIndicator size="large" color={Colors.button} />
          <Text style={{ color: Colors.text, marginTop: 8 }}>
            Loading profile…
          </Text>
        </View>
      </Screen>
    );
  }

  // Only the gesture opens Debug (no visible button)
  const canOpenDebug = __DEV__ || isAdminLocal;

  return (
    <Screen showBack onBack={() => navigation.goBack()}>
      {/* Invisible hotspot in the top-right */}
      <SecretTapHotspot
        enabled={canOpenDebug}
        onTrigger={() => navigation.navigate('Debug')}
      />

      <KeyboardAwareScrollView
        enableOnAndroid
        extraScrollHeight={120}
        extraHeight={120}
        keyboardShouldPersistTaps="handled"
        contentContainerStyle={styles.content}
        scrollEnabled
        enableAutomaticScroll
      >
        <TouchableOpacity
          activeOpacity={0.9}
          onLongPress={() => {
            const next = !isAdminCached();
            setAdminCached(next);
            setShowDebugButton(next);
            Alert.alert('Debug access', next ? 'Enabled' : 'Disabled');
          }}
        >
          <Text style={styles.title}>Profile</Text>
          {/* Optional tiny hint in dev; no visible Debug button */}
          {__DEV__ && (
            <Text style={{ color: '#9CA3AF', fontSize: 11, marginTop: -6 }}>
              (long-press title toggles Debug • 5 taps top-right opens Debug)
            </Text>
          )}
        </TouchableOpacity>

        {/* Unique ID */}
        <View style={styles.fieldBlock}>
          <Text style={styles.label}>Your User ID (share with friends)</Text>
          <View style={styles.idRow}>
            <Text style={styles.idValue}>{shortId || '—'}</Text>
          </View>
          <Text style={styles.helpText}>
            Friends can find you using this ID.
          </Text>
        </View>

        {/* Display Name */}
        <View style={styles.fieldBlock}>
          <FloatingLabelInput
            label="Display Name"
            value={displayName}
            onChangeText={setDisplayName}
            maxLength={60}
          />
        </View>

        {/* Favorite Verse (Reference) */}
        <View className="fieldBlock" style={styles.fieldBlock}>
          <FloatingLabelInput
            label="Favorite Verse (Reference)"
            placeholder="John 3: 15-16"
            value={verseRef}
            onChangeText={(v) => {
              setVerseRef(v);
              setVerseText('');
              setLastLookup({ ref: '', text: '' });
            }}
            maxLength={60}
          />
        </View>

        {/* Find Verse row */}
        <View
          style={{ marginTop: 8, flexDirection: 'row', alignItems: 'center' }}
        >
          <TouchableOpacity
            onPress={onFindVerse}
            disabled={finding || !verseRef.trim()}
            activeOpacity={0.9}
            style={[
              styles.findBtn,
              (finding || !verseRef.trim()) && { opacity: 0.6 },
            ]}
          >
            {finding ? (
              <ActivityIndicator color="#fff" />
            ) : (
              <Text style={styles.findBtnText}>Find Verse</Text>
            )}
          </TouchableOpacity>

          <TouchableOpacity
            onPress={() => {
              setVerseRef('');
              setVerseText('');
              setFindError('');
              setLastLookup({ ref: '', text: '' });
            }}
            style={{
              marginLeft: 12,
              paddingVertical: 10,
              paddingHorizontal: 12,
            }}
          >
            <Text style={styles.clearBtn}>Clear</Text>
          </TouchableOpacity>
        </View>

        {!!findError && (
          <Text style={{ color: '#a30000', marginTop: 6 }}>{findError}</Text>
        )}

        {/* Favorite Verse (Text) — read-only */}
        <View style={styles.fieldBlock}>
          <FloatingLabelInput
            label="Favorite Verse (Text)"
            value={verseText}
            editable={false}
            multiline
            autoGrow={false}
            minLines={3}
            maxLines={20}
            inputStyle={{ textAlignVertical: 'top', opacity: 0.9 }}
            maxLength={8000}
          />
          <Text style={styles.helpText}>
            Use “Find Verse” to fill this text. You can’t edit it manually.
          </Text>
        </View>

        {/* Save button */}
        <TouchableOpacity
          onPress={onSave}
          activeOpacity={0.9}
          disabled={!canSave}
          style={[styles.saveBtn, (!canSave || saving) && { opacity: 0.6 }]}
        >
          {saving ? (
            <ActivityIndicator color="#fff" />
          ) : (
            <>
              <Ionicons
                name="save-outline"
                size={18}
                color="#fff"
                style={{ marginRight: 8 }}
              />
              <Text style={styles.saveText}>Save Changes</Text>
            </>
          )}
        </TouchableOpacity>

        {showDebugButton && (__DEV__ || isAdminLocal) && (
          <TouchableOpacity
            onPress={() => navigation.navigate('Debug')}
            activeOpacity={0.9}
            style={[
              styles.saveBtn,
              { marginTop: 10, backgroundColor: '#374151' },
            ]}
          >
            <Ionicons
              name="construct-outline"
              size={18}
              color="#fff"
              style={{ marginRight: 8 }}
            />
            <Text style={styles.saveText}>Open Debug</Text>
          </TouchableOpacity>
        )}

        {/* 🔐 Account section */}
        <View style={[styles.fieldBlock, { marginTop: 24 }]}>
          <Text style={styles.sectionTitle}>Account</Text>

          {isAnonymous ? (
            <>
              <Text style={styles.accountInfo}>
                You’re currently using a guest account. If you delete the app or
                switch devices, you may lose your data (profile, journal,
                friends, etc.).
              </Text>
              <Text style={styles.accountInfo}>
                Create an account to safely keep your data and use the app
                across devices.
              </Text>

              <View style={{ height: 10 }} />

              <FloatingLabelInput
                label="Email for your account"
                value={accountEmailInput}
                onChangeText={setAccountEmailInput}
                keyboardType="email-address"
                autoCapitalize="none"
                autoCorrect={false}
                maxLength={120}
              />

              <View style={{ height: 8 }} />

              <FloatingLabelInput
                label="Choose a password"
                value={accountPasswordInput}
                onChangeText={setAccountPasswordInput}
                secureTextEntry
                maxLength={128}
              />

              <TouchableOpacity
                onPress={onUpgradeAccount}
                activeOpacity={0.9}
                disabled={
                  accountLoading ||
                  !accountEmailInput.trim() ||
                  accountPasswordInput.length < 6
                }
                style={[
                  styles.accountBtn,
                  (accountLoading ||
                    !accountEmailInput.trim() ||
                    accountPasswordInput.length < 6) && { opacity: 0.6 },
                ]}
              >
                {accountLoading ? (
                  <ActivityIndicator color="#fff" />
                ) : (
                  <Text style={styles.accountBtnText}>
                    Create account (recommended)
                  </Text>
                )}
              </TouchableOpacity>

              {/* sign out even as guest */}
              <TouchableOpacity
                onPress={onSignOut}
                activeOpacity={0.9}
                disabled={accountLoading}
                style={[
                  styles.accountSecondaryBtn,
                  { marginTop: 12 },
                  accountLoading && { opacity: 0.6 },
                ]}
              >
                <Text style={styles.accountSecondaryBtnText}>Sign out</Text>
              </TouchableOpacity>
            </>
          ) : (
            <>
              <Text style={styles.accountInfo}>
                You’re signed in as{' '}
                <Text style={{ fontWeight: '800' }}>
                  {authEmail || 'your account'}
                </Text>
                .
              </Text>
              <Text style={styles.accountInfo}>
                Your data is linked to this account. You can sign in on another
                device in the future to continue where you left off.
              </Text>

              <View style={{ height: 10 }} />

              <TouchableOpacity
                onPress={onSignOut}
                activeOpacity={0.9}
                disabled={accountLoading}
                style={[
                  styles.accountSecondaryBtn,
                  accountLoading && { opacity: 0.6 },
                ]}
              >
                <Text style={styles.accountSecondaryBtnText}>Sign out</Text>
              </TouchableOpacity>

              <TouchableOpacity
                onPress={onDeleteAccount}
                activeOpacity={0.9}
                disabled={accountLoading}
                style={[
                  styles.accountDangerBtn,
                  accountLoading && { opacity: 0.6 },
                ]}
              >
                <Text style={styles.accountDangerBtnText}>
                  Delete account permanently
                </Text>
              </TouchableOpacity>
            </>
          )}
        </View>
      </KeyboardAwareScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  content: {
    paddingHorizontal: 16,
    paddingBottom: Platform.OS === 'android' ? 96 : 32,
    paddingTop: 17,
  },
  title: {
    fontSize: 32,
    fontWeight: '800',
    color: Colors.button,
    marginBottom: 8,
  },
  fieldBlock: { marginTop: 12 },
  label: { marginBottom: 8, fontSize: 16, fontWeight: '800', color: '#1b2140' },
  idRow: {
    backgroundColor: '#e9eef3',
    borderRadius: 12,
    paddingHorizontal: 14,
    height: 48,
    alignItems: 'center',
    flexDirection: 'row',
  },
  idValue: { fontSize: 16, fontWeight: '800', color: Colors.button },
  helpText: { marginTop: 6, color: Colors.text, fontSize: 13 },
  saveBtn: {
    backgroundColor: Colors.button,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 16,
    opacity: 0.85,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  saveText: { color: '#fff', fontWeight: '800' },
  loadingWrap: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  findBtn: {
    backgroundColor: Colors.button,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  findBtnText: { color: '#fff', fontWeight: '800', opacity: 0.95 },
  clearBtn: {
    backgroundColor: '#fff',
    fontWeight: '800',
    borderRadius: 12,
    opacity: 0.7,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },

  // 🔐 Account styles
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1b2140',
    marginBottom: 6,
  },
  accountInfo: {
    color: Colors.text,
    fontSize: 13,
    marginBottom: 4,
  },
  accountBtn: {
    marginTop: 10,
    backgroundColor: Colors.button,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accountBtnText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 15,
  },
  accountSecondaryBtn: {
    marginTop: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#9CA3AF',
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  accountSecondaryBtnText: {
    color: '#374151',
    fontWeight: '700',
    fontSize: 14,
  },
  accountDangerBtn: {
    marginTop: 8,
    borderRadius: 14,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#B91C1C',
  },
  accountDangerBtnText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 14,
  },

  // 🔒 Secret hotspot in the top-right
  secretHotspot: {
    position: 'absolute',
    right: 0,
    top: Platform.select({ ios: 8, android: 8 }),
    width: 44,
    height: 44,
    zIndex: 10,
  },
});
